// Liste client-safe des montres de luxe du dashboard (Vidéo IA).
// Générée depuis lib/celebrity-db.ts (category: luxury_watch) — les ids doivent
// rester identiques : ils servent à retrouver les photos de référence dans le
// bucket Supabase celebrity-refs/{id}/ côté serveur.

export type WatchOption = { id: string; name: string; brand: string };

export const WATCH_OPTIONS: WatchOption[] = [
  { id: "air-king", name: "Air-King", brand: "Rolex" },
  { id: "cellini-moonphase", name: "Cellini Moonphase", brand: "Rolex" },
  { id: "cosmograph-daytona", name: "Cosmograph Daytona", brand: "Rolex" },
  { id: "datejust-36-palm", name: "Datejust 36 Palm", brand: "Rolex" },
  { id: "datejust-41", name: "Datejust 41", brand: "Rolex" },
  { id: "day-date-40-platine-ice-blue", name: "Day-Date 40 Platinum Ice Blue", brand: "Rolex" },
  { id: "day-date-president", name: "Day-Date President", brand: "Rolex" },
  { id: "deepsea-james-cameron", name: "Deepsea James Cameron", brand: "Rolex" },
  { id: "explorer-i-36", name: "Explorer I 36", brand: "Rolex" },
  { id: "explorer-ii", name: "Explorer II", brand: "Rolex" },
  { id: "gmt-master-ii-batman", name: "GMT-Master II Batman", brand: "Rolex" },
  { id: "gmt-master-ii-pepsi", name: "GMT-Master II Pepsi", brand: "Rolex" },
  { id: "gmt-master-ii-root-beer", name: "GMT-Master II Root Beer", brand: "Rolex" },
  { id: "milgauss", name: "Milgauss", brand: "Rolex" },
  { id: "oyster-perpetual", name: "Oyster Perpetual", brand: "Rolex" },
  { id: "oyster-perpetual-41-turquoise", name: "Oyster Perpetual 41 Turquoise", brand: "Rolex" },
  { id: "pearlmaster", name: "Pearlmaster", brand: "Rolex" },
  { id: "sea-dweller", name: "Sea-Dweller", brand: "Rolex" },
  { id: "sea-dweller-deepsea-d-blue", name: "Sea-Dweller Deepsea D-Blue", brand: "Rolex" },
  { id: "submariner-date", name: "Submariner Date", brand: "Rolex" },
  { id: "submariner-hulk", name: "Submariner Hulk", brand: "Rolex" },
  { id: "yacht-master-40", name: "Yacht-Master 40", brand: "Rolex" },
  { id: "yacht-master-ii", name: "Yacht-Master II", brand: "Rolex" },
  { id: "code-1159-chrono", name: "Code 11.59 Chrono", brand: "Audemars Piguet" },
  { id: "royal-oak", name: "Royal Oak", brand: "Audemars Piguet" },
  { id: "royal-oak-concept", name: "Royal Oak Concept", brand: "Audemars Piguet" },
  { id: "royal-oak-frosted-gold", name: "Royal Oak Frosted Gold", brand: "Audemars Piguet" },
  { id: "royal-oak-jumbo", name: "Royal Oak Jumbo", brand: "Audemars Piguet" },
  { id: "royal-oak-offshore-diver", name: "Royal Oak Offshore Diver", brand: "Audemars Piguet" },
  { id: "royal-oak-perpetual-calendar", name: "Royal Oak Perpetual Calendar", brand: "Audemars Piguet" },
  { id: "aquanaut", name: "Aquanaut", brand: "Patek Philippe" },
  { id: "aquanaut-chronograph-5968a", name: "Aquanaut Chronograph 5968A", brand: "Patek Philippe" },
  { id: "calatrava", name: "Calatrava", brand: "Patek Philippe" },
  { id: "calatrava-pilot-5524", name: "Calatrava Pilot 5524", brand: "Patek Philippe" },
  { id: "golden-ellipse", name: "Golden Ellipse", brand: "Patek Philippe" },
  { id: "grandmaster-chime", name: "Grandmaster Chime", brand: "Patek Philippe" },
  { id: "nautilus", name: "Nautilus", brand: "Patek Philippe" },
  { id: "nautilus-chrono", name: "Nautilus Chrono", brand: "Patek Philippe" },
  { id: "quantieme-perpetuel-chrono", name: "Quantieme Perpetuel Chrono", brand: "Patek Philippe" },
  { id: "twenty-4", name: "Twenty 4", brand: "Patek Philippe" },
  { id: "world-time-5230", name: "World Time 5230", brand: "Patek Philippe" },
  { id: "mp-05-laferrari", name: "MP-05 LaFerrari", brand: "Richard Mille" },
  { id: "rm-011-felipe-massa", name: "RM 011 Felipe Massa", brand: "Richard Mille" },
  { id: "rm-016", name: "RM 016", brand: "Richard Mille" },
  { id: "rm-027-tourbillon-nadal", name: "RM 027 Tourbillon Nadal", brand: "Richard Mille" },
  { id: "rm-030", name: "RM 030", brand: "Richard Mille" },
  { id: "rm-035-rafael-nadal", name: "RM 035 Rafael Nadal", brand: "Richard Mille" },
  { id: "rm-037", name: "RM 037", brand: "Richard Mille" },
  { id: "rm-055-bubba-watson", name: "RM 055 Bubba Watson", brand: "Richard Mille" },
  { id: "rm-07-02-pink-lady", name: "RM 07-02 Pink Lady", brand: "Richard Mille" },
  { id: "rm-11-05-gmt", name: "RM 11-05 GMT", brand: "Richard Mille" },
  { id: "rm-33-02", name: "RM 33-02", brand: "Richard Mille" },
  { id: "rm-50-03-mclaren", name: "RM 50-03 McLaren", brand: "Richard Mille" },
  { id: "rm-52-05-pharrell", name: "RM 52-05 Pharrell", brand: "Richard Mille" },
  { id: "rm-61-01-yohan-blake", name: "RM 61-01 Yohan Blake", brand: "Richard Mille" },
  { id: "rm-62-01", name: "RM 62-01", brand: "Richard Mille" },
  { id: "rm-67-01-extra-flat", name: "RM 67-01 Extra Flat", brand: "Richard Mille" },
  { id: "big-bang", name: "Big Bang", brand: "Hublot" },
  { id: "big-bang-ferrari", name: "Big Bang Ferrari", brand: "Hublot" },
  { id: "big-bang-integral-ceramic", name: "Big Bang Integral Ceramic", brand: "Hublot" },
  { id: "big-bang-king-power", name: "Big Bang King Power", brand: "Hublot" },
  { id: "big-bang-meca-10", name: "Big Bang Meca-10", brand: "Hublot" },
  { id: "big-bang-tourbillon", name: "Big Bang Tourbillon", brand: "Hublot" },
  { id: "big-bang-unico", name: "Big Bang Unico", brand: "Hublot" },
  { id: "classic-fusion", name: "Classic Fusion", brand: "Hublot" },
  { id: "classic-fusion-blue-titanium", name: "Classic Fusion Blue Titanium", brand: "Hublot" },
  { id: "classic-fusion-orlinski", name: "Classic Fusion Orlinski", brand: "Hublot" },
  { id: "mp-07", name: "MP-07", brand: "Hublot" },
  { id: "mp-09-tourbillon-bi-axis", name: "MP-09 Tourbillon Bi-Axis", brand: "Hublot" },
  { id: "spirit-of-big-bang", name: "Spirit of Big Bang", brand: "Hublot" },
  { id: "spirit-of-big-bang-sapphire", name: "Spirit of Big Bang Sapphire", brand: "Hublot" },
  { id: "baignoire", name: "Baignoire", brand: "Cartier" },
  { id: "ballon-bleu", name: "Ballon Bleu", brand: "Cartier" },
  { id: "ballon-bleu-or-rose", name: "Ballon Bleu Or Rose", brand: "Cartier" },
  { id: "cle-de-cartier", name: "Clé de Cartier", brand: "Cartier" },
  { id: "panthere", name: "Panthère", brand: "Cartier" },
  { id: "pasha-chronograph", name: "Pasha Chronograph", brand: "Cartier" },
  { id: "ronde-louis-cartier", name: "Ronde Louis Cartier", brand: "Cartier" },
  { id: "santos", name: "Santos", brand: "Cartier" },
  { id: "santos-skeleton-noire", name: "Santos Skeleton Noire", brand: "Cartier" },
  { id: "santos-dumont", name: "Santos-Dumont", brand: "Cartier" },
  { id: "tank", name: "Tank", brand: "Cartier" },
  { id: "tank-americaine-xl", name: "Tank Américaine XL", brand: "Cartier" },
  { id: "tank-cintree", name: "Tank Cintrée", brand: "Cartier" },
  { id: "tank-francaise", name: "Tank Française", brand: "Cartier" },
  { id: "constellation", name: "Constellation", brand: "Omega" },
  { id: "de-ville-tresor", name: "De Ville Trésor", brand: "Omega" },
  { id: "seamaster-diver-300m", name: "Seamaster Diver 300M", brand: "Omega" },
  { id: "seamaster-planet-ocean", name: "Seamaster Planet Ocean", brand: "Omega" },
  { id: "speedmaster-moonwatch", name: "Speedmaster Moonwatch", brand: "Omega" },
  { id: "big-pilot", name: "Big Pilot", brand: "IWC" },
  { id: "portugieser-chrono", name: "Portugieser Chrono", brand: "IWC" },
  { id: "carrera", name: "Carrera", brand: "TAG Heuer" },
  { id: "monaco", name: "Monaco", brand: "TAG Heuer" },
  { id: "black-bay-58", name: "Black Bay 58", brand: "Tudor" },
];

export const WATCH_BRANDS = ["Rolex","Audemars Piguet","Patek Philippe","Richard Mille","Hublot","Cartier","Omega","IWC","TAG Heuer","Tudor"];
